---
title: "CO2 Emission in Indonesia"
author: "yanurhi"
date: "2022-12-17"
output: html_document
---

## install & load packages
```{r install packages}
install.packages("tidyverse")
```

```{r loading packages}
library(tidyverse)

```

## membaca .csv
```{r membaca csv}
data_emisi <- read.csv(file = "co2_emmision_indonesia.csv", header = T, sep = ";")
print(data_emisi)
```

## memeriksa nama
```{r memeriksa nama}
names(data_emisi)
```

## penggantian nama kolom
```{r ganti nama kolom}
data_emisi <- data_emisi %>%
  rename (Negara = Country,
          Tahun = Date,
          CO2.Total.MetricTons = CO2.Total.Mt,
          CO2.Kg.per.PPPofGDP = Co2.Kg.1000.,
          CO2.Tons.per.capita = CO2.Tons.per.capita
          )
names(data_emisi)
```

## memeriksa tipe data
```{r memeriksa tipe data}
tibble(data_emisi)
```

## mengubah tipe data
```{r mengubah tipe data}
data_emisi$CO2.Total.MetricTons = as.character(data_emisi$CO2.Total.MetricTons)
data_emisi$Tahun = as.character(data_emisi$Tahun)
data_emisi$CO2.Tons.per.capita = as.character(data_emisi$CO2.Tons.per.capita)
tibble(data_emisi)

```

## mengedit data, menghilangkan tanda koma di total CO2 Metrik Ton
```{r hapus koma}
data_emisi$CO2.Total.MetricTons <- gsub('[^[:alnum:] ]','',data_emisi$CO2.Total.MetricTons)
tibble(data_emisi)
```

## visualisasi
```{r diagram batang}
scale <- data.frame(Tahun = c(data_emisi$Tahun),
                    CO2.Tons.per.capita = c(data_emisi$CO2.Tons.per.capita))
scale <- dplyr::filter(scale,Tahun >= 2000)

ggplot(scale, aes(x=Tahun ,y=CO2.Tons.per.capita))+
  geom_col()+
  geom_bar(stat = "identity", fill='coral', alpha=0.9)+
  geom_text(aes(label = CO2.Tons.per.capita),size = 3, nudge_y = +0.7)+
  labs(title = "Emisi CO2 Negara Indonesia",
       subtitle = "Tahun 2000 - 2021",
     x = "Tahun",
     y = "CO2 (Tons per Capita)")+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.7))+
  coord_flip()+
  theme_classic() +
  theme(
    plot.title = element_text(size = 15, face = "bold"),
    plot.subtitle = element_text(size = 12),
    axis.title.y = element_text(size = 10),
    axis.text.y = element_text(size = 8),
    axis.title.x = element_text(size = 10),
    axis.text.x = element_blank(),
    aspect.ratio = 1/1
  )

scale2 <- data.frame(Tahun = c(data_emisi$Tahun),
                    CO2.Total.MetricTons = c(data_emisi$CO2.Total.MetricTons))
scale2 <- dplyr::filter(scale2,Tahun >= 2000)

ggplot(scale2, aes(x=Tahun ,y=CO2.Total.MetricTons))+
  geom_col()+
  geom_bar(stat = "identity", fill='chartreuse', alpha=0.9)+
  geom_text(aes(label = CO2.Total.MetricTons),size = 3, nudge_y =+1.3)+
  labs(title = "Emisi CO2 Negara Indonesia",
       subtitle = "Tahun 2000 - 2021",
       x = "Tahun",
       y = "CO2 (Metric Tons)")+
  coord_flip()+
  theme_classic() +
  theme(
    plot.title = element_text(size = 15, face = "bold"),
    plot.subtitle = element_text(size = 12),
    axis.title.y = element_text(size = 10),
    axis.text.y = element_text(size = 8),
    axis.title.x = element_text(size = 10),
    axis.text.x = element_blank(),
    aspect.ratio = 1/1
  )
```

























